const oracledb = require('oracledb');
const loadEnvFile = require('./utils/envUtil');

const envVariables = loadEnvFile('./.env');

// Database configuration setup. Ensure your .env file has the required database credentials.
const dbConfig = {
    user: envVariables.ORACLE_USER,
    password: envVariables.ORACLE_PASS,
    connectString: `${envVariables.ORACLE_HOST}:${envVariables.ORACLE_PORT}/${envVariables.ORACLE_DBNAME}`
};


// ----------------------------------------------------------
// Wrapper to manage OracleDB actions, simplifying connection handling.
async function withOracleDB(action) {
    let connection;
    try {
        connection = await oracledb.getConnection(dbConfig);
        return await action(connection);
    } catch (err) {
        console.error(err);
        throw err;
    } finally {
        if (connection) {
            try {
                await connection.close();
            } catch (err) {
                console.error(err);
            }
        }
    }
}


// ----------------------------------------------------------
// Core functions for database operations
// Modify these functions, especially the SQL queries, based on your project's requirements and design.
async function testOracleConnection() {
    return await withOracleDB(async (connection) => {
        return true;
    }).catch(() => {
        return false;
    });
}

module.exports = {
    testOracleConnection
};

//
//// Add a new function for user registration
//async function registerUser(email, password) {
//    try {
//        // Add your validation logic, password hashing, etc. here if needed
//
//        return await withOracleDB(async (connection) => {
//            const result = await connection.execute(
//                `INSERT INTO USERS (email, password) VALUES (:email, :password)`,
//                [email, password],
//                { autoCommit: true }
//            );
//
//            return result.rowsAffected && result.rowsAffected > 0;
//        });
//    } catch (error) {
//        console.error('User Registration Error:', error);
//        return false;
//    }
//}
//
//async function initiateDemotable() {
//    try {
//        return await withOracleDB(async (connection) => {
//            // Check if the USERS table exists
//            const tableExists = await checkIfTableExists(connection, 'USERS');
//
//            // If the USERS table doesn't exist, create it
//            if (!tableExists) {
//                const result = await connection.execute(`
//                    CREATE TABLE USERS (
//                        id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
//                        email VARCHAR2(255) UNIQUE NOT NULL,
//                        password VARCHAR2(255) NOT NULL
//                    )
//                `);
//
//                console.log('USERS table created successfully.');
//                return true;
//            }
//
//            console.log('USERS table already exists.');
//            return true;
//        });
//    } catch (error) {
//        console.error('Error initiating USERS table:', error);
//        return false;
//    }
//}
//
//async function checkIfTableExists(connection, tableName) {
//    const result = await connection.execute(
//        `SELECT table_name FROM all_tables WHERE table_name = :tableName`,
//        [tableName]
//    );
//
//    return result.rows.length > 0;
//}
